version: "3"
services: 
  worker-service:
    build:
      context: ./SingleThreadCrackHash/WorkerProject/Worker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
  manager-service:
    build: 
      context: ./SingleThreadCrackHash/ManagerProject/Manager
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: always