version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbit
    #    healthcheck:
    #      test: rabbitmq-diagnostics -q ping
    #      interval: 30s
    #      timeout: 30s
    #      retries: 3
    networks:
      - main
  
  worker-service:
     build:
       context: ./MultiThreadCrackHash/WorkerProject/Worker
       dockerfile: Dockerfile
     ports:
       - "8081:8081"
     restart: always
     networks:
       - main

  manager-service:
    build: 
      context: ./MultiThreadCrackHash/ManagerProject/Manager
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: always
    networks:
      - main
    depends_on:
      - rabbitmq
    #environment:
    #  - LOGGING_LEVEL_ROOT=DEBUG
  

networks:
  main:
    driver: bridge

